# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.0.594"

package:
  name: dbt-protos
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dbt-protos/dbt_protos-${{ version }}.tar.gz
  sha256: 23140898ff8bcbb9291f087c9f344c0a4a4279e31639916196ff98fb2e41967d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - protobuf >=3.17.1

tests:
  - python:
      imports:
        - dbtlabs
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/dbt-labs/proto-python-public
  repository: https://github.com/dbt-labs/proto-python-public
  documentation: https://github.com/dbt-labs/proto-python-public/blob/main/README.md
  license: Apache-2.0
  license_file: LICENSE
  summary: Public proto bindings for dbt
  description: |
    Public proto bindings for dbt.

extra:
  recipe-maintainers:
    - rxm7706
